[log]
level=INFO
file_ok=True

; taiga项目
name_taiga=project-taiga-web
file_name_taiga=taiga-web

;日志个数
num = 10

[taiga]
; taiga数据库，类型为PostgreSQL
host=192.168.88.130
port=5432
user=taiga
password=taiga_db_cwg
database=taiga